"""
Knowledge-base tools for the co-worker agent.

`search_knowledge` is TF-IDF retrieval over the per-case wiki chunk index.
`read_note` looks up a specific note (by source_id + note_ref) via
`wiki/note_links.json` and returns its markdown plus the rows it backs.
"""

from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional

from core.cases.case_store import CaseStore
from core.knowledge import search_case_wiki


_store = CaseStore()


def _note_key(value: Any) -> str:
    raw = str(value or "").strip().lower().replace("note", "").strip()
    raw = re.sub(r"[^a-z0-9.]+", "", raw)
    return raw[:-2] if raw.endswith(".0") else raw


SEARCH_KNOWLEDGE_SPEC: Dict[str, Any] = {
    "name": "search_knowledge",
    "description": (
        "Search the case knowledge base — the per-source wiki pages, notes, "
        "narrative sections (auditor / directors), merged statements, "
        "analytics summary, and credit memo — and return the top-K chunks "
        "ranked by relevance. Each hit has a snippet, source PDF, page range, "
        "and a wiki path you can quote. Use this when the analyst asks about "
        "qualitative content (notes, accounting policies, auditor comments, "
        "related-party disclosures, going concern, etc.) or anything that "
        "isn't a structured ratio."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "Natural-language query. Single keywords also work.",
            },
            "k": {
                "type": "integer",
                "description": "Max number of chunks to return. Default 5, max 12.",
                "minimum": 1,
                "maximum": 12,
            },
        },
        "required": ["query"],
    },
}


def search_knowledge(case_id: str, query: str, k: int = 5) -> Dict[str, Any]:
    case_root = _store._case_path(case_id)
    wiki_root = case_root / "wiki"
    if not wiki_root.exists():
        return {
            "result": {
                "available": False,
                "reason": (
                    "Case knowledge base has not been built yet. The wiki is "
                    "generated by the analysis pipeline — analyst must run "
                    "/analyze (or POST /cases/{id}/knowledge/rebuild)."
                ),
            },
            "citations": [],
        }

    k = max(1, min(int(k or 5), 12))
    raw = search_case_wiki(case_root, query, limit=k)
    hits: List[Dict[str, Any]] = raw.get("results") or []

    result = {
        "available": True,
        "query": raw.get("query", query),
        "count": len(hits),
        "hits": [
            {
                "title": h.get("title"),
                "doc_type": h.get("doc_type"),
                "snippet": h.get("snippet"),
                "score": h.get("score"),
                "source_id": h.get("source_id"),
                "source_file": h.get("source_file"),
                "page_range": h.get("page_range"),
                "wiki_path": h.get("path"),
            }
            for h in hits
        ],
    }

    citations: List[Dict[str, Any]] = [
        {
            "kind": "wiki",
            "title": h.get("title"),
            "wiki_path": h.get("path"),
            "source_id": h.get("source_id"),
            "source_file": h.get("source_file"),
            "page_range": h.get("page_range"),
        }
        for h in hits
    ]
    return {"result": result, "citations": citations}


# ---- read_note ---------------------------------------------------------------

READ_NOTE_SPEC: Dict[str, Any] = {
    "name": "read_note",
    "description": (
        "Fetch a specific note from one of the source PDFs by its note number, "
        "and return the markdown body, page range, and the statement rows that "
        "reference it. Use after the analyst asks about a specific note (e.g. "
        "'what does note 12 say about going concern'), or after a get_statement "
        "call surfaces a row with a note_ref worth opening. Pass either "
        "source_id+note_ref (preferred — get source_id from earlier tool "
        "results or search_knowledge citations), or just note_ref to get all "
        "matches across sources."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "note_ref": {
                "type": "string",
                "description": "Note number, e.g. '12', '4.2', or 'note 12'.",
            },
            "source_id": {
                "type": "string",
                "description": (
                    "Optional — restrict the lookup to one source PDF. "
                    "When omitted, returns matches across all sources."
                ),
            },
        },
        "required": ["note_ref"],
    },
}


def read_note(case_id: str, note_ref: str, source_id: Optional[str] = None) -> Dict[str, Any]:
    wiki_root = _store._case_path(case_id) / "wiki"
    links_path = wiki_root / "note_links.json"
    if not links_path.exists():
        return {
            "result": {
                "available": False,
                "reason": (
                    "No note links on disk yet — the case wiki has not been "
                    "built. Analyst needs to run /analyze first."
                ),
            },
            "citations": [],
        }

    try:
        links = (json.loads(links_path.read_text(encoding="utf-8")) or {}).get("links") or []
    except json.JSONDecodeError as e:
        return {
            "result": {"available": False, "reason": f"Corrupt note_links.json: {e}"},
            "citations": [],
        }

    key = _note_key(note_ref)
    if not key:
        return {
            "result": {"available": False, "reason": "Empty note_ref."},
            "citations": [],
        }

    sid_filter = (source_id or "").strip() or None
    matches = [
        link for link in links
        if _note_key(link.get("note_ref") or link.get("note_no")) == key
        and (not sid_filter or link.get("source_id") == sid_filter)
    ]
    if not matches:
        available = sorted({
            (link.get("source_id"), _note_key(link.get("note_ref") or link.get("note_no")))
            for link in links
        })
        return {
            "result": {
                "available": False,
                "reason": (
                    f"No note matches note_ref='{note_ref}'"
                    + (f" within source_id={source_id}" if sid_filter else "")
                    + "."
                ),
                "available_notes": [
                    {"source_id": sid, "note_ref": nk} for sid, nk in available[:25]
                ],
            },
            "citations": [],
        }

    # Group by (source_id, note_wiki_path) so a note referenced by N rows is
    # returned once, with all referencing rows listed under it.
    by_note: Dict[tuple, Dict[str, Any]] = {}
    for link in matches:
        nkey = (link.get("source_id"), link.get("note_wiki_path"))
        entry = by_note.setdefault(nkey, {
            "source_id": link.get("source_id"),
            "source_file": link.get("source_file"),
            "note_no": link.get("note_no"),
            "note_title": link.get("note_title"),
            "note_page_range": link.get("note_page_range"),
            "note_wiki_path": link.get("note_wiki_path"),
            "markdown": "",
            "referenced_by_rows": [],
        })
        entry["referenced_by_rows"].append({
            "statement": link.get("statement"),
            "statement_title": link.get("statement_title"),
            "row_label": link.get("row_label"),
            "canonical_code": link.get("canonical_code"),
            "row_page": link.get("row_page"),
        })

    # Hydrate markdown bodies. Note files live under wiki/<note_wiki_path>.
    for entry in by_note.values():
        path = entry["note_wiki_path"]
        if not path:
            continue
        md_path = (wiki_root / path).resolve()
        try:
            md_path.relative_to(wiki_root.resolve())
        except ValueError:
            continue
        if md_path.exists() and md_path.is_file():
            try:
                entry["markdown"] = md_path.read_text(encoding="utf-8")
            except OSError:
                entry["markdown"] = ""

    notes = list(by_note.values())
    citations = [
        {
            "kind": "note",
            "source_id": n["source_id"],
            "source_file": n["source_file"],
            "note_no": n["note_no"],
            "note_title": n["note_title"],
            "page_range": n["note_page_range"],
            "wiki_path": n["note_wiki_path"],
        }
        for n in notes
    ]

    return {
        "result": {
            "available": True,
            "note_ref": note_ref,
            "match_count": len(notes),
            "notes": notes,
        },
        "citations": citations,
    }
