"""
Credit-report tools for the co-worker agent.

Read-only access to `cases/<id>/reports/latest.json` — the section-by-section
credit analysis report generated by `core/report/generator.py`. The agent can
list available sections (cheap TOC fetch) and pull one section's markdown by
code (Executive Credit View, Borrower Profile, Financial Snapshot, etc.).

Write-side regenerate_report_section is intentionally NOT exposed yet — that
belongs in Phase 4 once we have the confirm-before-mutate UI in place.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from core.cases.case_store import CaseStore


_store = CaseStore()


def _load_latest_report(case_id: str) -> Optional[Dict[str, Any]]:
    path = _store._case_path(case_id) / "reports" / "latest.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


# ---- list_report_sections ----------------------------------------------------

LIST_REPORT_SECTIONS_SPEC: Dict[str, Any] = {
    "name": "list_report_sections",
    "description": (
        "Return the table of contents for the latest credit analysis report — "
        "section code, title, number, and source (llm / deterministic / "
        "error). Use first when the analyst asks about a section but you "
        "don't know the code, or to confirm the report has been generated."
    ),
    "input_schema": {"type": "object", "properties": {}},
}


def list_report_sections(case_id: str) -> Dict[str, Any]:
    report = _load_latest_report(case_id)
    if not report:
        return {
            "result": {
                "available": False,
                "reason": (
                    "No credit report on disk yet. The analyst needs to "
                    "generate it via the Report page (POST "
                    f"/cases/{case_id}/report/generate)."
                ),
            },
            "citations": [],
        }

    sections: List[Dict[str, Any]] = report.get("sections") or []
    toc = [
        {
            "code": s.get("code"),
            "number": s.get("number"),
            "title": s.get("title"),
            "source": s.get("source"),
            "has_error": bool(s.get("error")),
            "markdown_length": len(s.get("markdown") or ""),
        }
        for s in sections
    ]
    result = {
        "available": True,
        "entity_name": report.get("entity_name"),
        "fys": report.get("fys"),
        "template": report.get("template"),
        "generated_at": report.get("generated_at"),
        "section_count": len(sections),
        "sections": toc,
    }
    citations = [{
        "kind": "report",
        "path": f"cases/{case_id}/reports/latest.json",
        "template": report.get("template"),
    }]
    return {"result": result, "citations": citations}


# ---- get_report_section ------------------------------------------------------

GET_REPORT_SECTION_SPEC: Dict[str, Any] = {
    "name": "get_report_section",
    "description": (
        "Return the full markdown of one section from the latest credit "
        "report. Use when the analyst asks 'what does the report say about X' "
        "or wants the existing committee narrative on a topic. Look up the "
        "section code via list_report_sections first if you're not sure of "
        "it (common codes: executive_credit_view, borrower_profile, "
        "financial_snapshot, liquidity_assessment, leverage_assessment)."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "code": {
                "type": "string",
                "description": "Section code from list_report_sections.",
            },
            "max_chars": {
                "type": "integer",
                "description": (
                    "Optional cap on returned markdown length. Defaults to "
                    "8000, which fits comfortably in context."
                ),
                "minimum": 200,
                "maximum": 30000,
            },
        },
        "required": ["code"],
    },
}


def get_report_section(case_id: str, code: str, max_chars: int = 8000) -> Dict[str, Any]:
    report = _load_latest_report(case_id)
    if not report:
        return {
            "result": {
                "available": False,
                "reason": "No credit report on disk yet — generate it first.",
            },
            "citations": [],
        }
    code = (code or "").strip()
    if not code:
        return {
            "result": {"available": False, "reason": "Empty section code."},
            "citations": [],
        }

    sections: List[Dict[str, Any]] = report.get("sections") or []
    match = next((s for s in sections if (s.get("code") or "") == code), None)
    if match is None:
        return {
            "result": {
                "available": False,
                "reason": f"No section with code='{code}' in the latest report.",
                "available_codes": [s.get("code") for s in sections if s.get("code")],
            },
            "citations": [],
        }

    max_chars = max(200, min(int(max_chars or 8000), 30000))
    markdown = match.get("markdown") or ""
    truncated = len(markdown) > max_chars
    body = markdown[:max_chars] + ("\n\n…(truncated)" if truncated else "")

    result = {
        "available": True,
        "code": match.get("code"),
        "number": match.get("number"),
        "title": match.get("title"),
        "source": match.get("source"),
        "error": match.get("error"),
        "markdown": body,
        "truncated": truncated,
        "markdown_length_total": len(markdown),
    }
    citations = [{
        "kind": "report_section",
        "path": f"cases/{case_id}/reports/latest.json",
        "section_code": match.get("code"),
        "section_title": match.get("title"),
    }]
    return {"result": result, "citations": citations}
