"""
Financial statement text-extractor for z124 XBRL→PDF renderings.

These PDFs are auto-generated by ACRA from the XBRL filing — their tables
are clean and text-extractable with pdfplumber. The challenge is detecting
column headers (perimeter × period) and mapping raw labels → canonical codes.
"""

from __future__ import annotations

import re
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .canonical_map import resolve_label, statement_for

logger = logging.getLogger(__name__)

# Suppress noisy pdfplumber font warnings
logging.getLogger("pdfminer").setLevel(logging.ERROR)


# ---- Statement detection -------------------------------------------------------

STATEMENT_ANCHORS: List[Tuple[str, re.Pattern]] = [
    ("sofp", re.compile(r"STATEMENT\s+OF\s+FINANCIAL\s+POSITION", re.I)),
    ("soci", re.compile(r"STATEMENT\s+OF\s+(?:PROFIT\s+OR\s+LOSS\s+AND\s+)?COMPREHENSIVE\s+INCOME", re.I)),
    ("socf", re.compile(r"STATEMENT\s+OF\s+CASH\s+FLOWS?", re.I)),
    ("soce", re.compile(r"STATEMENT\s+OF\s+CHANGES\s+IN\s+EQUITY", re.I)),
]

END_OF_STATEMENT = re.compile(
    r"(annexed notes form an integral part|the accompanying notes form an integral part|"
    r"summary of significant accounting policies|notes to (?:the )?financial statements|"
    r"these unaudited financial statements were authorised)",
    re.I,
)

YEAR_RE = re.compile(r"\b(20\d{2})\b")
PERIMETER_TOKENS = ("group", "company")
NUMBER_RE = re.compile(
    r"""
    (?:\(\s*-?\s*[\d,]+(?:\.\d+)?\s*\)) |    # (1,234) negative
    (?:-?\s*[\d,]+(?:\.\d+)?)            |    # 1,234.56 / -123
    (?:\*)                                    # * "less than S$1"
    """,
    re.VERBOSE,
)
NOTE_PREFIX_RE = re.compile(r"^\s*\d{1,2}[a-z]?\s+")  # leading note number on a line

CURRENCY_RE = re.compile(r"\b(S\$|SGD|USD|HKD|RMB)\b", re.I)


@dataclass
class ColumnHeader:
    perimeter: str   # "group" | "company"
    fy: str          # "FY2023"
    period_end: Optional[str] = None  # placeholder for downstream alignment


@dataclass
class ExtractedLine:
    raw_label: str
    canonical_code: Optional[str]
    label: Optional[str]
    statement: str
    values: Dict[str, float]   # column_id -> value
    note: Optional[str] = None
    page: int = 0
    confidence: float = 1.0
    flags: List[str] = field(default_factory=list)
    # Statement-flow rendering metadata — drive the as-filed view in the UI.
    display_order: int = 0
    section_path: List[str] = field(default_factory=list)
    indent_level: int = 1
    row_type: str = "line"  # line | subtotal | total | section_header


@dataclass
class FSExtraction:
    source_file: str
    entity_name: str = ""
    uen: str = ""
    framework: str = "SFRS"
    currency: str = "SGD"
    audited: bool = False
    consolidated: bool = False
    period_end_primary: str = ""
    columns: List[ColumnHeader] = field(default_factory=list)
    lines: List[ExtractedLine] = field(default_factory=list)
    review_flags: List[Dict[str, Any]] = field(default_factory=list)
    extraction_method: str = "text"
    # Per-page raw text — kept for narrative extraction and raw.txt dumps.
    # Not serialised by `to_dict()` to keep the IngestionResult JSON compact.
    pages_text: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "meta": {
                "source_file": self.source_file,
                "entity_name": self.entity_name,
                "uen": self.uen,
                "framework": self.framework,
                "currency": self.currency,
                "audited": self.audited,
                "consolidated": self.consolidated,
                "period_end_primary": self.period_end_primary,
                "extraction_method": self.extraction_method,
            },
            "columns": [
                {"id": f"{c.perimeter}_{c.fy}", "perimeter": c.perimeter, "fy": c.fy,
                 "period_end": c.period_end}
                for c in self.columns
            ],
            "lines": [
                {
                    "raw_label": ln.raw_label,
                    "canonical_code": ln.canonical_code,
                    "label": ln.label,
                    "statement": ln.statement,
                    "note": ln.note,
                    "page": ln.page,
                    "confidence": round(ln.confidence, 2),
                    "values": ln.values,
                    "flags": ln.flags,
                    "display_order": ln.display_order,
                    "section_path": ln.section_path,
                    "indent_level": ln.indent_level,
                    "row_type": ln.row_type,
                }
                for ln in self.lines
            ],
            "review_flags": self.review_flags,
        }


# ---- Statement-flow classification --------------------------------------------

# Top-level totals — render at indent 0 with double-rule formatting upstream.
_TOP_TOTAL_CODES = frozenset({
    "bs_total_assets", "bs_total_liab", "bs_total_equity", "bs_net_assets",
    "pl_pat", "pl_tci", "cf_cash_end",
})

# Subtotal lines — render bold at one indent in from the section.
_SUBTOTAL_CODES = frozenset({
    "bs_total_ca", "bs_total_nca", "bs_total_cl", "bs_total_ncl",
    "pl_gross_profit", "pl_total_expenses", "pl_pbt",
    "cf_operating", "cf_investing", "cf_financing", "cf_net_change_cash",
})

# Section banners we recognise in SFRS(I) statements. Lower-case lookup key →
# display name; sub-sections (Current / Non-current splits) get nested under
# their parent banner so the rendered view shows ASSETS > Current Assets > ...
_SECTION_BANNERS: Dict[str, str] = {
    "assets": "Assets",
    "current assets": "Current Assets",
    "non-current assets": "Non-current Assets",
    "non current assets": "Non-current Assets",
    "liabilities": "Liabilities",
    "current liabilities": "Current Liabilities",
    "non-current liabilities": "Non-current Liabilities",
    "non current liabilities": "Non-current Liabilities",
    "equity": "Equity",
    "capital and reserves": "Capital and Reserves",
    "reserves": "Reserves",
    "cash flows from operating activities": "Operating Activities",
    "cash flows used in operating activities": "Operating Activities",
    "cash flows from investing activities": "Investing Activities",
    "cash flows used in investing activities": "Investing Activities",
    "cash flows from financing activities": "Financing Activities",
    "cash flows used in financing activities": "Financing Activities",
    "operating activities": "Operating Activities",
    "investing activities": "Investing Activities",
    "financing activities": "Financing Activities",
}

_SUB_SECTIONS = frozenset({
    "Current Assets", "Non-current Assets",
    "Current Liabilities", "Non-current Liabilities",
    "Capital and Reserves", "Reserves",
})


def _detect_section_header(label: str) -> Optional[str]:
    """Return the canonical section display name when `label` is a section banner."""
    if not label:
        return None
    s = re.sub(r"\s+", " ", label).strip().rstrip(":").lower()
    return _SECTION_BANNERS.get(s)


def _classify_row_type(code: Optional[str], raw_label: str) -> str:
    if code and code in _TOP_TOTAL_CODES:
        return "total"
    if code and code in _SUBTOTAL_CODES:
        return "subtotal"
    if raw_label.strip().lower().startswith("total "):
        return "subtotal"
    return "line"


def _indent_for(row_type: str, section_path: List[str]) -> int:
    if row_type in ("section_header", "total"):
        return 0
    if row_type == "subtotal":
        return max(1, len(section_path))
    return max(1, len(section_path))


def _emit_lines_from_block(
    *,
    block_buffer: List[Tuple[int, str]],
    current_columns: List["ColumnHeader"],
    current_stmt: str,
    ext: "FSExtraction",
    start_order: int,
    ocr_mode: bool = False,
) -> int:
    """
    Walk the buffered raw lines of one statement block and append enriched
    ExtractedLine entries to `ext.lines`. Returns the next `display_order`
    for the caller to thread into subsequent calls (same statement).
    """
    current_section: List[str] = []
    order = start_order
    for page_no, raw_line in block_buffer:
        label, note, num_tokens = _split_label_and_numbers(raw_line)

        # Label-only line: could be a section banner. Anything else we drop —
        # the parser already skips wraps via the column-header check below.
        if label and not num_tokens:
            banner = _detect_section_header(label)
            if not banner:
                continue
            if banner in _SUB_SECTIONS and current_section:
                current_section = [current_section[0], banner]
            else:
                current_section = [banner]
            parent_path = current_section[:-1]
            ext.lines.append(ExtractedLine(
                raw_label=label,
                canonical_code=None,
                label=banner,
                statement=current_stmt,
                values={},
                page=page_no,
                display_order=order,
                section_path=list(parent_path),
                indent_level=len(parent_path),
                row_type="section_header",
                confidence=1.0,
                flags=[],
            ))
            order += 1
            continue

        if not label or not num_tokens:
            continue
        if label.lower() in ("s$", "sgd", "note", "group", "company") or YEAR_RE.fullmatch(label.strip()):
            continue

        nums = [_parse_number(t) for t in num_tokens]
        nums = [n for n in nums if n is not None]
        if not nums:
            continue

        code, conf = resolve_label(label)
        values: Dict[str, float] = {}
        offset = len(current_columns) - len(nums)
        if offset < 0:
            nums = nums[-len(current_columns):]
            offset = 0
        for i, v in enumerate(nums):
            col = current_columns[i + offset]
            values[f"{col.perimeter}_{col.fy}"] = v

        row_type = _classify_row_type(code, label)
        if row_type == "subtotal" and len(current_section) >= 2:
            deepest = current_section[-1].lower()
            if deepest in label.lower():
                current_section = current_section[:-1]
        if row_type == "total":
            section_for_row = list(current_section)
            current_section = []
        else:
            section_for_row = list(current_section)

        confidence = conf if code else 0.4
        flags: List[str] = [] if code else ["unmapped_label"]
        if ocr_mode:
            confidence = round(confidence * 0.85, 2)
            flags = ["ocr"] + flags

        ext.lines.append(ExtractedLine(
            raw_label=label,
            canonical_code=code,
            label=label.title() if code else label,
            statement=current_stmt,
            values=values,
            note=note,
            page=page_no,
            display_order=order,
            section_path=section_for_row,
            indent_level=_indent_for(row_type, section_for_row),
            row_type=row_type,
            confidence=confidence,
            flags=flags,
        ))
        order += 1
    return order


# ---- Number parsing -----------------------------------------------------------

def _parse_number(token: str) -> Optional[float]:
    t = token.strip()
    if t == "*":
        return 0.0  # "Denotes less than S$1"
    neg = False
    if t.startswith("(") and t.endswith(")"):
        neg = True
        t = t[1:-1]
    t = t.replace(",", "").replace(" ", "")
    if not re.fullmatch(r"-?\d+(?:\.\d+)?", t):
        return None
    try:
        v = float(t)
    except ValueError:
        return None
    return -v if neg else v


def _split_label_and_numbers(line: str) -> Tuple[str, Optional[str], List[str]]:
    """
    Returns (label, note_number, numeric_tokens).
    Heuristic: take all trailing numeric tokens that are separated by whitespace,
    and treat the rest as label. The first numeric token immediately after the
    label *may* be a note number (1-2 digits, integer) — we hand both possibilities
    back to the caller.
    """
    s = line.strip()
    if not s:
        return "", None, []
    # collect numeric tokens from the right
    parts = s.split()
    nums: List[str] = []
    while parts and (NUMBER_RE.fullmatch(parts[-1]) or parts[-1] == "*" or _looks_like_continued_paren(parts)):
        # handle case where "(1,234)" was split across spaces: "(1,234" "1,234)"
        tok = parts.pop()
        nums.insert(0, tok)
    label_tokens = parts
    label = " ".join(label_tokens).strip()

    note = None
    # detect note number: an unaccompanied 1-2 digit integer at the end of the label
    # (z124 PDFs often place note number between label and first amount)
    if label_tokens and re.fullmatch(r"\d{1,2}[a-z]?", label_tokens[-1]):
        note = label_tokens[-1]
        label = " ".join(label_tokens[:-1]).strip()
    return label, note, nums


def _looks_like_continued_paren(parts: List[str]) -> bool:
    """Detect leftover '(123' or '456)' fragments — rare in z124 PDFs but safe."""
    if not parts:
        return False
    p = parts[-1]
    return bool(re.fullmatch(r"\(?-?[\d,]+\)?", p))


# ---- Header detection ----------------------------------------------------------

def _detect_columns(block_lines: List[str]) -> List[ColumnHeader]:
    """
    Inspect the first ~10 lines of a statement block to deduce column structure.
    Returns columns left-to-right. Handles common patterns:

        Group   Company
        Note 2023  2023  2022
              S$   S$   S$
    or
        Note 2023 2022      (single-perimeter, Company)
              S$  S$

    Strategy: prefer the year-line with the MOST years (the column header proper),
    not the first one we see — "AS AT 31 DECEMBER 2023" also has a year and would
    otherwise win.
    """
    perimeter_line = None
    year_line = None
    best_year_count = 0
    DATE_END_RE = re.compile(r"^3[01][./]1[12][./](20\d{2})$")

    def _extract_column_years(line: str) -> List[str]:
        """Pull column-year identifiers: bare years or end-of-period dates only."""
        toks = line.split()
        out: List[str] = []
        for t in toks:
            t_clean = t.strip(",.;:()")
            if re.fullmatch(r"20\d{2}", t_clean):
                out.append(t_clean)
                continue
            m = DATE_END_RE.match(t_clean)
            if m:
                out.append(m.group(1))
        return out

    for ln in block_lines[:12]:
        low = ln.lower()
        if perimeter_line is None and re.search(r"\b(group|company)\b", low) and len(ln.split()) <= 6:
            perimeter_line = ln
        col_years = _extract_column_years(ln)
        if col_years and len(ln.split()) <= 10:
            tie_break = 1 if low.lstrip().startswith("note") else 0
            score = len(col_years) * 10 + tie_break
            if score > best_year_count:
                best_year_count = score
                year_line = ln

    years = _extract_column_years(year_line) if year_line else []
    cols: List[ColumnHeader] = []
    if not years:
        return cols

    if perimeter_line:
        # Use positional ordering: split the perimeter line into tokens and align by year count
        perims_in_order = [w.lower() for w in perimeter_line.split() if w.lower() in PERIMETER_TOKENS]
        if not perims_in_order:
            perims_in_order = ["company"]
    else:
        perims_in_order = ["company"]

    # Common layout: [group_y1, company_y1, company_y2]  -> if "group company" + 3 years
    if perims_in_order == ["group", "company"] and len(years) == 3:
        cols.append(ColumnHeader("group",   f"FY{years[0]}"))
        cols.append(ColumnHeader("company", f"FY{years[1]}"))
        cols.append(ColumnHeader("company", f"FY{years[2]}"))
    elif perims_in_order == ["group", "company"] and len(years) == 4:
        # Group y1 y2  Company y1 y2
        cols.append(ColumnHeader("group",   f"FY{years[0]}"))
        cols.append(ColumnHeader("group",   f"FY{years[1]}"))
        cols.append(ColumnHeader("company", f"FY{years[2]}"))
        cols.append(ColumnHeader("company", f"FY{years[3]}"))
    elif perims_in_order == ["group"] and len(years) >= 1:
        for y in years:
            cols.append(ColumnHeader("group", f"FY{y}"))
    else:
        # default: all columns are Company
        for y in years:
            cols.append(ColumnHeader("company", f"FY{y}"))
    return cols


# ---- Main parser ---------------------------------------------------------------

# Characters that can appear in an SG entity name. Allows brackets
# (`(Singapore)`), slashes, ampersands; never lower-case (every SG entity name
# on z124 covers is upper-cased).
_NAME_CHARS = r"A-Z0-9 &'.,\-()/"
_NAME_LINE_RE = re.compile(rf"^[{_NAME_CHARS}]+$")
_HEX_HASH_RE = re.compile(r"^[0-9a-f]{16,}$")
_ENTITY_SUFFIX_RE = re.compile(
    r"\b("
    r"PTE\.?\s*LTD\.?|PRIVATE\s+LIMITED|LIMITED|LTD\.?|"
    r"LIMITED\s+LIABILITY\s+PARTNERSHIP|LLP|"
    r"PUBLIC\s+COMPANY\s+LIMITED|PLC|"
    r"INC\.?|INCORPORATED|"
    r"HOLDINGS|GROUP"
    r")\b",
    re.IGNORECASE,
)
_COVER_ANCHOR_RE = re.compile(
    r"^("
    r"Registration\s+Number|"
    r"UNAUDITED\s+FINANCIAL\s+STATEMENTS|"
    r"AUDITED\s+FINANCIAL\s+STATEMENTS|"
    r"FINANCIAL\s+STATEMENTS|"
    r"Year\s+ended|"
    r"For\s+the\s+(?:financial\s+)?year\s+ended"
    r")",
    re.IGNORECASE,
)


def _extract_entity_name_from_cover(text: str) -> Optional[str]:
    """
    Extract the entity name from a z124 / UFS cover page.

    The XBRL render lays the cover out as:

        <ENTITY NAME LINE 1>
        <ENTITY NAME LINE 2 — often "(JURISDICTION) PTE. LTD.">
        Registration Number: <UEN>
        FINANCIAL STATEMENTS
        Year ended <date>

    Strategy:
      1. Anchor-walk: find the first cover anchor line (Registration Number /
         FINANCIAL STATEMENTS / Year ended). Walk back over up to 4 lines
         collecting consecutive all-caps name-like lines; stitch them together
         and verify the result has a known entity suffix.
      2. Forward scan: if anchor-walk fails (anchor missing), find the first
         contiguous run of name-like lines that ends with an entity suffix.

    Both paths skip hex hashes (pdfplumber sometimes lifts a hidden hash from
    the page header) and page-number lines.
    """
    lines = [ln.strip() for ln in text.split("\n")]
    n = len(lines)

    def _name_candidate(ln: str) -> bool:
        return bool(ln) and bool(_NAME_LINE_RE.match(ln)) and not _HEX_HASH_RE.match(ln)

    # 1. Anchor-walk backwards from the first cover anchor we see.
    for i, ln in enumerate(lines[:30]):
        if not _COVER_ANCHOR_RE.match(ln):
            continue
        parts: List[str] = []
        for j in range(i - 1, max(-1, i - 5), -1):
            cand = lines[j]
            if not cand:
                if parts:
                    break
                continue
            if not _name_candidate(cand):
                if parts:
                    break
                continue
            parts.insert(0, cand)
        joined = " ".join(parts).strip()
        if joined and _ENTITY_SUFFIX_RE.search(joined):
            return joined
        # Anchor was present but no name above it (or no suffix). Stop trying
        # other anchors so we don't latch onto something downstream.
        break

    # 2. Forward scan as a fallback.
    for i in range(min(n, 30)):
        if not _name_candidate(lines[i]):
            continue
        parts = []
        j = i
        while j < n and j - i < 3 and _name_candidate(lines[j]):
            parts.append(lines[j])
            joined = " ".join(parts)
            if _ENTITY_SUFFIX_RE.search(joined):
                return joined
            j += 1

    return None


def _detect_meta(full_text: str) -> Dict[str, Any]:
    """Pull entity name, UEN, currency, framework, consolidated flag from the cover."""
    meta: Dict[str, Any] = {"framework": "SFRS", "currency": "SGD", "audited": False, "consolidated": False}
    name = _extract_entity_name_from_cover(full_text)
    if name:
        meta["entity_name"] = name
    m = re.search(r"Registration Number[:\s]+(\d{8,10}[A-Z])", full_text, re.I)
    if m:
        meta["uen"] = m.group(1)
    m = re.search(r"Year ended (\d{1,2} \w+ \d{4})", full_text, re.I)
    if m:
        meta["period_end_primary"] = m.group(1)
    if re.search(r"AND ITS SUBSIDIARY|AND ITS SUBSIDIARIES", full_text):
        meta["consolidated"] = True
    if re.search(r"UNAUDITED FINANCIAL STATEMENTS", full_text, re.I):
        meta["audited"] = False
    elif re.search(r"AUDITED FINANCIAL STATEMENTS|INDEPENDENT AUDITOR'S REPORT", full_text, re.I):
        meta["audited"] = True
    if re.search(r"Singapore Financial Reporting Standard.*International|SFRS\(I\)", full_text, re.I):
        meta["framework"] = "SFRS(I)"
    return meta


def extract_fs_z124(pdf_path: Path) -> FSExtraction:
    """
    Parse a z124 XBRL→PDF rendering. Returns FSExtraction with canonical-mapped lines.
    """
    import pdfplumber
    pdf_path = Path(pdf_path)
    ext = FSExtraction(source_file=str(pdf_path))

    # 1. Cover-page meta from first 3 pages
    cover_text = ""
    pages_text: List[str] = []
    with pdfplumber.open(pdf_path) as pdf:
        for i, p in enumerate(pdf.pages):
            t = p.extract_text() or ""
            pages_text.append(t)
            if i < 3:
                cover_text += "\n" + t

    meta = _detect_meta(cover_text)
    ext.entity_name = meta.get("entity_name", "")
    ext.uen = meta.get("uen", "")
    ext.framework = meta.get("framework", "SFRS")
    ext.audited = meta.get("audited", False)
    ext.consolidated = meta.get("consolidated", False)
    ext.period_end_primary = meta.get("period_end_primary", "")
    ext.pages_text = pages_text

    # 2. Walk pages, slice statement blocks
    current_stmt: Optional[str] = None
    current_columns: List[ColumnHeader] = []
    block_buffer: List[Tuple[int, str]] = []  # (page, line)
    order_per_stmt: Dict[str, int] = {}

    def flush_block():
        nonlocal current_stmt, current_columns, block_buffer
        if not current_stmt or not block_buffer:
            block_buffer = []
            return
        # detect columns from the first ~8 buffered lines
        first_lines = [ln for _, ln in block_buffer[:10]]
        cols = _detect_columns(first_lines)
        if cols and not current_columns:
            current_columns = cols
            if not ext.columns:
                ext.columns = cols
            else:
                # union — preserves earlier columns if statement appears twice (rare)
                for c in cols:
                    if not any(x.perimeter == c.perimeter and x.fy == c.fy for x in ext.columns):
                        ext.columns.append(c)

        if not current_columns:
            ext.review_flags.append({
                "severity": "medium",
                "message": f"Could not detect columns for {current_stmt}",
                "source": str(pdf_path.name),
            })
            block_buffer = []
            return

        start_order = order_per_stmt.get(current_stmt, 0)
        next_order = _emit_lines_from_block(
            block_buffer=block_buffer,
            current_columns=current_columns,
            current_stmt=current_stmt,
            ext=ext,
            start_order=start_order,
            ocr_mode=False,
        )
        order_per_stmt[current_stmt] = next_order
        block_buffer = []
        current_columns = []  # reset for next statement instance

    for page_no, text in enumerate(pages_text, start=1):
        for raw_line in text.split("\n"):
            line = raw_line.rstrip()
            if not line.strip():
                continue
            # detect statement boundary
            new_stmt = None
            for code, pat in STATEMENT_ANCHORS:
                if pat.search(line):
                    new_stmt = code
                    break
            if new_stmt:
                flush_block()
                current_stmt = new_stmt if new_stmt in ("sofp", "soci", "socf") else None
                current_columns = []
                continue
            # end-of-statement / start of notes
            if current_stmt and END_OF_STATEMENT.search(line):
                flush_block()
                current_stmt = None
                continue
            if current_stmt:
                block_buffer.append((page_no, line))

    flush_block()

    # 3. sanity flags
    if not any(ln.canonical_code == "bs_total_assets" for ln in ext.lines):
        ext.review_flags.append({
            "severity": "low",
            "message": "Total assets not captured — verify SoFP extraction",
            "source": str(pdf_path.name),
        })

    return ext


def extraction_to_periods(extraction: FSExtraction) -> List[Dict[str, Any]]:
    """Pivot the column-major output into perimeter+FY 'periods' blocks the agents expect."""
    by_period: Dict[str, Dict[str, Any]] = {}
    for c in extraction.columns:
        key = f"{c.perimeter}_{c.fy}"
        by_period[key] = {
            "perimeter": c.perimeter,
            "fy": c.fy,
            "period_end": c.period_end,
            "currency": extraction.currency,
            "statements": {"sofp": [], "soci": [], "soce": [], "socf": []},
        }
    for ln in extraction.lines:
        if ln.statement not in ("sofp", "soci", "soce", "socf"):
            continue
        for col_id, val in ln.values.items():
            if col_id not in by_period:
                continue
            by_period[col_id]["statements"][ln.statement].append({
                "canonical_code": ln.canonical_code,
                "label": ln.raw_label,
                "amount": val,
                "note": ln.note,
                "confidence": ln.confidence,
            })
    return list(by_period.values())
